        sudo cp -r pck3r /bin/
        echo pck3r copied ...
        sudo cp -r pck3r-help /bin/
        echo pak3r-help copied ...
        echo pck3r dependences ...
        sudo apt install wget
        sudo apt install curl
        sudo apt install libgtk-3-dev
        